language: android
jdk: oraclejdk8

before_install:
  - ls -l /usr/local
  - sudo rm -rf /usr/local/maven*
  - sudo apt-get update -qq
  - sudo apt-get install maven

#cache:
#  directories:
#  - $HOME/.m2
